name: CI


on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Get Public IP of Host Machine
        id: get_public_ip
        run: |
          PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
          echo "Public_IP_HOST_MACHINE= ${PUBLIC_IP}" >> $GITHUB_ENV
        
      - name: Set up Docker Compose and Build Services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for MongoDB to be ready
        run: |
          sleep 30

      - name: Verify if containers are running
        run: |
          docker ps

      - name: Stop Docker Compose services
        run: |
          docker-compose down
